### PR TITLE
Style/home

### PR DESCRIPTION
**Pull request by CBradsen**
## Types of changes made?
Styling for accessibility

## What does this PR do?
- Creates a separate Box component which simplifies the code
- Updates colors of icons to #383240, which is the color of the footer of the DMC website. This makes them easier to read. 
- Replaces icons with all Ionicons for consistency
- Uses windowWidth and windowHeight with Dimensions from react-native for adjusting to various phone sizes or even for an ipad
- Uses Pressable instead of Touch Opacity which allows for user-feedback when a button is pushed. Icon will become a slightly lighter color and the shadow will become slightly more glowy.
  
## Relevant Tickets?

- Questions/Comments/Relevant Screenshots?
Was sad to let the meditation person icon go, but Ionicons didn't have anything like it, and this keeps it consistent, if not a little more boring. We can try to put meditating person icon back later if seen as valuable. 

image

### CODE REVIEW

**Comment by CBradsen** [comment]
Tests not passing due to the App path issue again. 
Note: I moved App.js back into Components to get it to show on the ios simulator. 

image

**Comment by CBradsen** [comment]
Here's what we tried Saturday evening to get tests passing: 

Branch is up to date with main. 
Sam and I tried changing the AppEntry.js file back to this: 

```
import registerRootComponent from 'expo/build/launch/registerRootComponent';

import App from '../../App';
registerRootComponent(App);
```

we tried to add this to App.js: 

```
import { AppRegistry } from 'react-native';

AppRegistry.registerComponent('YourAppName', () => App);
```
None of that worked. 
Moving App.js back to components allowed both npm run ios and npm run web to work. But not pass tests on github CI.

**Review by sarahcatherine311 — APPROVED** [review]
Just had to rewrite the tests to get it to pass. It wasn't picking up on the testIDs. Thanks for all the hard work Carol!

**Review by SamanthaMcElhinney — APPROVED** [review]
Love the hoover effect on the main page! Nice work.

**Pull request merged**
