### PR TITLE
Feature/gallery

### PR DESCRIPTION
**Pull request by CBradsen**
## Types of changes made?
- [X] functionality

## What does this PR do?
- Adds functionality
Creates a gallery page to show photos from Drala Center
  
## Relevant Tickets?
- Finishes Gallery

image

### CODE REVIEW

**Comment by CBradsen** [comment]
Tests aren't passing because of the App route, maybe: 
image

**Review by sarahcatherine311 — APPROVED** [review]
At long last. Can't believe we had to move App back.

**Comment by CBradsen** [comment]
Changing files paths and the test did it! thanks, Sarah and Alejandro for trouble shooting this!

**Review by SamanthaMcElhinney — APPROVED** [review]
Nice job figuring this out!!!!

**Pull request merged**
