### PR TITLE
fix: Resize photos in gallery and add 3 more

### PR DESCRIPTION
**Pull request by CBradsen**
## Types of changes made?
- [X] functionality fix, to the photos that were too large, creating problems for deployment.

## What does this PR do?
- Updates the photos to smaller sizes, all under 500 KB now. 
- Adds three more photos

  
## Relevant Tickets?
image

### CODE REVIEW

**Comment by CBradsen** [comment]
The failed tests are for the attempt to deploy on Netlify. 
Here is the log of that: 
image

**Comment by SamanthaMcElhinney** [comment]
Nice fix! Thanks for doing this Carol.

**Review by SamanthaMcElhinney — APPROVED** [review]
Looks good! Nice work.

**Review by sarahcatherine311 — APPROVED** [review]
Great work y'all!

**Pull request merged**
