### PR TITLE
Ci setup

### PR DESCRIPTION
**Pull request by CBradsen**
## Types of changes made?
- [x] testing
- [ ] documentation
- [ ] react/rails
- [ ] functionality

## What does this PR do?
sets up CI and cypress within it

## Relevant Tickets?
- Finishes iteration or ticket for
- Questions/Comments/Relevant Screenshots?

### CODE REVIEW

**Review by AlejandroLopez1992 — APPROVED** [review]
Great job troubleshooting to get this to work!

**Review by AlejandroLopez1992 — APPROVED** [review]
Great job troubleshooting through this despite all the hurtles!!

**Comment by SamanthaMcElhinney** [comment]
Nice work Carol! Thanks for setting this up. Great Job debugging and troubleshooting.

**Review by AlejandroLopez1992 — APPROVED** [review]

**Review by sarahcatherine311 — APPROVED** [review]
Well done! Looks great, thanks for all the hard work on this.

**Review by SamanthaMcElhinney — APPROVED** [review]
Great job debugging!

**Pull request merged**
